### PR TITLE
JPL's CNEOS Scout API

### PR DESCRIPTION
**Pull request by LuEdRaMo**

### CODE REVIEW

**Comment by PerezHz** [comment]
Hey, many thanks for this addition @LuEdRaMo! I think this change is pretty straight-forward so it LGTM. I would only point to tests failing on nightly, but I'd suggest to wait and see if those errors fade away, as is usually the case.

**Comment by LuEdRaMo** [comment]
I just bumped the patch version so this is ready. Once the errors with nightly are sorted out we can merge this. Btw, some tests fail because of Coveralls, do you know why?

**Comment by PerezHz** [comment]
>I just bumped the patch version so this is ready. Once the errors with nightly are sorted out we can merge this. Btw, some tests fail because of Coveralls, do you know why?

There's an ongoing issue with coveralls (see e.g. [here](https://github.com/lemurheavy/coveralls-public/issues/1716)), the workaround that I've found so far has been to avoid triggering CI simultaneously with push and pull_requests events. I can push that fix here, confirm that it works, and then merge.

**Comment by PerezHz** [comment]
Tests are passing now, except nightly, but I think we can address those on another PR, so I'll go and merge this. Again, thanks a lot!

**Pull request merged**
