### PR TITLE
Add ooe_tbl function to get ELEMENTS tables

### PR DESCRIPTION
**Pull request by david-macmahon**
This adds support for retrieving Osculating Orbital Elements tables.

### CODE REVIEW

**Review by PerezHz — APPROVED** [review]
Hey, many thanks for adding the osculating elements table API @david-macmahon! I would only suggest to add an order of magnitude check, say, that the semimajor axis of the object at the selected epoch has roughly the expected value, i.e., something like
```julia
@test a_jwst ≈ #= reference value =#
```
where a_jwst is the fetched value. But probably this check can fail at some point, since it depends on the latest orbit solution used for the object? Still, I think a quick check like this can be valuable. Otherwise, LGTM!

**Comment by david-macmahon** [comment]
I guess I could check that JWST's semi-major axis is between 1.0 and 1.2 AU.  That's a very generous range, but for a sanity check maybe it's OK.  I'm not sure how tight would be "safe".  Maybe 1.05 and 1.15 AU?  What do you think?

**Comment by david-macmahon** [comment]
Actually, if we did it for a "historic" date we could probably check very closely.  I don't know whether the historic values change, and if they do then by how much.  Here's what the commentary (aka "object data") says currently:

```
 Trajectory files                             Start (TDB)         End (TDB) 
 ----------------------------------------  -----------------  -----------------
 DEFINITIVE_EPHEMERIS_202135913-2024077    2021-Dec-25 13:01  2024-Mar-25 00:01
 28D_BURN_PREDICT_SK_2024078500000_05U     2024-Mar-25 00:01  2024-Apr-22 00:01
 2Y_SCHEDULE_2024078500000_05U.V0.1        2024-Apr-22 00:01  2026-Mar-24 23:59
```

**Comment by PerezHz** [comment]
Many thanks for checking this! From the object data it looks like if we take a date within the interval of the first row (definitive ephemeris) we should be fine. I think checking the semimajor axis with an absolute tolerance of ~0.05 au as you suggest should do the trick for us.

**Comment by PerezHz** [comment]
Merging, thanks again @david-macmahon!

**Pull request merged**
